version: 2.1
jobs:
  build:
    docker:
      - image: pierre124/dockerhub:latest
        auth:
          username: pierre124
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Activate Env/Install Requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Install Docker
          command: |
            apt-get update
            apt-get install --no-install-recommends -y sudo
            sudo apt-get update
            sudo apt-get install --no-install-recommends docker-ce docker-ce-cli containerd.io
            docker run hello-world
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push pierre124/dockerhub:latest
      - store_artifacts:
          path: test-reports/
          destination: python_app

