# Generated by Django 3.0 on 2021-10-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20211002_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
